In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("india_tech_jobs.csv")
df

,job_title,experience_years,education,primary_skill,skills_count,city,state,company,company_size,work_mode,salary_lpa
0,QA Engineer,4,B.Tech,Git,8,Bengaluru,Karnataka,Capgemini India,Enterprise,Onsite,14.3
1,Python Developer,9,BCA,Power BI,2,Chennai,Tamil Nadu,Razorpay,Medium,Onsite,21.9
2,Full Stack Developer,7,BCA,Spark,7,Delhi,Delhi,Accenture India,Large,Hybrid,15.3
3,Backend Developer,10,B.Sc CS,PyTorch,5,Delhi,Delhi,PhonePe,Medium,Hybrid,23.1
4,Full Stack Developer,3,B.Sc CS,SQL,11,Indore,Madhya Pradesh,Zomato,Startup,Onsite,7.4
...,...,...,...,...,...,...,...,...,...,...,...
59995,Cybersecurity Analyst,4,MCA,Linux,7,Delhi,Delhi,Cognizant,Enterprise,Hybrid,9.4
59996,Frontend Developer,4,B.Tech,Java,8,Pune,Maharashtra,Zomato,Startup,Hybrid,13.1
59997,Backend Developer,4,MCA,React,6,Bengaluru,Karnataka,Capgemini India,Startup,Hybrid,11.3
59998,ML Engineer,15,BCA,Git,2,Bengaluru,Karnataka,Flipkart,Medium,Hybrid,37.9
59999,Data Analyst,6,BCA,Node.js,4,Gurugram,Haryana,LTIMindtree,Large,Hybrid,17.1

In [3]:
df.describe()

       experience_years  skills_count    salary_lpa
count      60000.000000  60000.000000  60000.000000
mean           7.483417      6.988567     19.093458
std            4.605028      3.156818      8.665266
min            0.000000      2.000000      3.000000
25%            3.000000      4.000000     11.800000
50%            7.000000      7.000000     19.100000
75%           11.000000     10.000000     26.300000
max           15.000000     12.000000     42.400000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_title         60000 non-null  object
 1   experience_years  60000 non-null  int64
 2   education         60000 non-null  object
 3   primary_skill     60000 non-null  object
 4   skills_count      60000 non-null  int64
 5   city              60000 non-null  object
 6   state             60000 non-null  object
 7   company           60000 non-null  object
 8   company_size      60000 non-null  object
 9   work_mode         60000 non-null  object
 10  salary_lpa        60000 non-null  float64
dtypes: float64(1), int64(2), object(8)
memory usage: 5.0+ MB

In [5]:
df['job_title'].value_counts()

job_title
Cloud Engineer           4423
DevOps Engineer          4394
Java Developer           4349
Full Stack Developer     4341
Cybersecurity Analyst    4317
Data Analyst             4299
ML Engineer              4286
Backend Developer        4270
QA Engineer              4264
Software Engineer        4246
Python Developer         4239
Android Developer        4219
Frontend Developer       4188
Data Scientist           4165
Name: count, dtype: int64

In [6]:
df['city'].value_counts()

city
Noida        6735
Pune         6722
Mumbai       6712
Indore       6708
Delhi        6677
Bengaluru    6638
Hyderabad    6621
Gurugram     6598
Chennai      6589
Name: count, dtype: int64

In [7]:
df['state'].value_counts()

state
Maharashtra       13434
Uttar Pradesh      6735
Madhya Pradesh     6708
Delhi              6677
Karnataka          6638
Telangana          6621
Haryana            6598
Tamil Nadu         6589
Name: count, dtype: int64